<a href="https://colab.research.google.com/github/OrangeP1anet/math-python/blob/main/lesson5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 逆行列を解くプログラム

---


今回は行列を扱うためNumpyを使うこととする。  
行列への入力は

> a11 a12  
> a21 a22

 とする。

## Installation

---


```
import numpy as np
```

In [ ]:
import numpy as np

#numpy配列を宣言、初期化
arr = np.array([[0, 1], [2, 3]])

#値を入力
arr[0][0] = int(input("a11="))
arr[0][1] = int(input("a12="))
arr[1][0] = int(input("a21="))
arr[1][1] = int(input("a22="))
b = (int(input("mod=")))

#
a = (arr[0][0] * arr[1][1]) - (arr[0][1] * arr[1][0])

#Nを法とした逆数を求める
arr_inv = np.array([[arr[1][1], -arr[0][1]], [-arr[1][0], arr[0][0]]])
ans = arr_inv * abs(a)

print()
print(arr)
print()
print(ans)
print()

#最小正剰余の計算
while ans[0][0] > b or ans[0][1] < 0 or ans[1][0] < 0 or ans[1][1] > b:
  if ans[0][0] > b:
    ans[0][0] -= b

  if ans[0][1] < 0:
    ans[0][1] += b

  if ans[1][0] < 0:
    ans[1][0] += b

  if ans[1][1] > b:
    ans[1][1] -= b

a = (arr[0][0] * arr[1][1]) - (arr[0][1] * arr[1][0])

print(b,"を法として")
print(arr)
print("の逆行列", "(mod", b, ")", "は")
print(ans)

a11=2
a12=3
a21=7
a22=8
mod=26

[[2 3]
 [7 8]]

[[ 40 -15]
 [-35  10]]

26 を法として
[[2 3]
 [7 8]]
の逆行列 (mod 26 ) は
[[14 11]
 [17 10]]


## 逆行列を解くプログラム(Numpy無しバージョン)

未完成

---


行列への入力は 

a11 a12

a21 a22 とする。