<a href="https://colab.research.google.com/github/OrangeP1anet/math-python/blob/main/lesson5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 逆行列を解くプログラム

---


今回は行列を扱うためNumpyを使うこととする。  
行列への入力は

> a11 a12  
> a21 a22

 とする。

## Installation

---


```
import numpy as np
import sympy as sp
```

In [1]:
import sympy as sp
import numpy as np

# numpy配列を宣言、初期化
arr = np.array([[1, 2], [3, 4]])

# 入力
arr[0][0] = int(input("Enter a11: "))
arr[0][1] = int(input("Enter a12: "))
arr[1][0] = int(input("Enter a21:"))
arr[1][1] = int(input("Enter a22:"))
mod = (int(input("Enter mod: ")))

# インバース|A|を求める
a = (arr[0][0] * arr[1][1]) - (arr[0][1] * arr[1][0]) % mod
kx = sp.gcdex(a, mod)[0]

# Nを法とした逆数
arr_inv = np.array([[arr[1][1], -arr[0][1]], [-arr[1][0], arr[0][0]]])

# 結果の出力
print(mod,"を法として")
print(arr)
print("の逆行列", "(mod", mod, ")", "は")
print(((kx * arr_inv) % mod) % mod)7

Enter a11: 2
Enter a12: 3
Enter a21:7
Enter a22:8
Enter mod: 26
26 を法として
[[2 3]
 [7 8]]
の逆行列 (mod 26 ) は
[[14 11]
 [17 10]]


## numpyだけバージョン

In [ ]:
import numpy as np

a = [] # 割られる数
b = [] # 割る数
q = [] # 商
r = [] # 余り
kx = [] # xの係数
ky = [] # yの係数
i = 0 # リストの先頭に位置する
j = 0 # リストの先頭に位置する

#numpy配列を宣言、初期化
arr = np.array([[0, 1], [2, 3]])

#値を入力
arr[0][0] = int(input("a11="))
arr[0][1] = int(input("a12="))
arr[1][0] = int(input("a21="))
arr[1][1] = int(input("a22="))
mod = (int(input("mod = ")))


# インバース|A|を求める
a.append((arr[0][0] * arr[1][1]) - (arr[0][1] * arr[1][0])%mod)
b.append(mod)
q.append(a[i] // b[i]) # 商をリストの先頭に追加
r.append(a[i] % b[i])  # 余りをリストの先頭に追加

while r[i] != 0:
  a.append(b[i]) # 割られる数を割る数にする
  b.append(r[i]) # 割る数をあまりにする
  i += 1         # リストの位置を一つ更新
  q.append(a[i] // b[i])
  r.append(a[i] % b[i])

i -= 1
kx.append(1)
ky.append(-q[i])

while i != 0:
  i -= 1 # 一行下へ
  kx.append(ky[j])
  ky.append(kx[j] + (q[i])*(-ky[j]))
  j += 1 # リストの位置を一つ更新

# 求めたインバース|A|をaに代入
a = kx[j]

# Nを法とした逆数
arr_inv = np.array([[arr[1][1], -arr[0][1]], [-arr[1][0], arr[0][0]]])
ans = arr_inv * a #逆行列

# 最小正剰余の計算
ans = ans % mod

ans = arr_inv * a
print()
print(arr)
print()
print(ans)
print()

# 最小正剰余の計算
ans = ans % mod

print(mod,"を法として")
print(arr)
print("の逆行列", "(mod", mod, ")", "は")
print(ans)

a11=2
a12=3
a21=7
a22=8
mod = 26

[[2 3]
 [7 8]]

[[ 40 -15]
 [-35  10]]

26 を法として
[[2 3]
 [7 8]]
の逆行列 (mod 26 ) は
[[14 11]
 [17 10]]
