<a href="https://colab.research.google.com/github/OrangeP1anet/math-python/blob/main/lesson6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 連立方程式を解くプログラム

---

行列を扱うため [NumPy](https://note.nkmk.me/python-numpy-matrix/) を使用する。   
入力は

> | a11 a12 | * |x|　≡　|a|　(modX)  
> | a21 a22 |　|y|　　　|b|

 とし、この時のx,yを求める。

## Installation

---


```
import numpy as np
import sympy as sp
```

In [7]:
import sympy as sp
import numpy as np

# numpy配列を宣言、初期化
arr = np.array([[1, 2], [3, 4]])
arr_ab = np.array([[1], [2]])

# 入力
arr[0][0] = int(input("Enter a11: "))
arr[0][1] = int(input("Enter a12: "))
arr[1][0] = int(input("Enter a21: "))
arr[1][1] = int(input("Enter a22: "))
arr_ab[0][0] = int(input("Enter a: "))
arr_ab[1][0] = int(input("Enter b: "))
mod = (int(input("Enter mod: ")))

# インバース|A|を求める
a = (arr[0][0] * arr[1][1]) - (arr[0][1] * arr[1][0]) % mod
kx = sp.gcdex(a, mod)[0]

# Nを法とした逆数
arr_inv = np.array([[arr[1][1], -arr[0][1]], [-arr[1][0], arr[0][0]]])

# 逆行列
ans = ((kx * arr_inv) % mod) % mod

# 行列の積はnp.dotを使用し、二つ以上のNumpy配列を引数に取る
ans = np.dot(ans, arr_ab)

# 最小正剰余として結果を出力
print(f"(x, y) (mod{mod}) は")
print(ans % mod)

Enter a11: 2
Enter a12: 3
Enter a21: 7
Enter a22: 8
Enter a: 1
Enter b: 2
Enter mod: 26
(x, y) (mod26) は
[[10]
 [11]]


## numpyだけバージョン

In [ ]:
import numpy as np

a = [] # 割られる数
b = [] # 割る数
q = [] # 商
r = [] # 余り
kx = [] # xの係数
ky = [] # yの係数
i = 0 # リストの先頭に位置する
j = 0 # リストの先頭に位置する

# numpy配列を二つ宣言、初期化
# 一方は2*2の行列、もう一方は1*2の行列
arr = np.array([[0, 1], [2, 3]])
arr_ab = np.array([[1], [2]])

# それぞれの値を入力
arr[0][0] = int(input("a11 = "))
arr[0][1] = int(input("a12 = "))
arr[1][0] = int(input("a21 = "))
arr[1][1] = int(input("a22 = "))
arr_ab[0][0] = int(input("a = "))
arr_ab[1][0] = int(input("b = "))
mod = (int(input("mod = ")))

# インバース|A|を求める
a.append((arr[0][0] * arr[1][1]) - (arr[0][1] * arr[1][0])%mod)
b.append(mod)
q.append(a[i] // b[i]) # 商をリストの先頭に追加
r.append(a[i] % b[i])  # 余りをリストの先頭に追加

while r[i] != 0:
  a.append(b[i]) # 割られる数を割る数にする
  b.append(r[i]) # 割る数をあまりにする
  i += 1         # リストの位置を一つ更新
  q.append(a[i] // b[i])
  r.append(a[i] % b[i])

i -= 1
kx.append(1)
ky.append(-q[i])

while i != 0:
  i -= 1 # 一行下へ
  kx.append(ky[j])
  ky.append(kx[j] + (q[i])*(-ky[j]))
  j += 1 # リストの位置を一つ更新

# 求めたインバース|A|をaに代入
a = kx[j]

# Nを法とした逆数
arr_inv = np.array([[arr[1][1], -arr[0][1]], [-arr[1][0], arr[0][0]]])
temp = arr_inv * a #逆行列

# 最小正剰余の計算
temp = temp % mod

# 結果の出力
print()
print("行列")
print(arr)
print()
print("逆行列")
print(temp)
print()

# 行列の積はnp.dotを使用し、二つ以上のNumpy配列を引数に取る
ans = np.dot(temp, arr_ab)

# 最小正剰余の計算
ans = ans % mod

# 結果の出力
print(f"(x, y) (mod{mod}) は")
print(ans)

a11 = 2
a12 = 3
a21 = 7
a22 = 8
a = 1
b = 2
mod = 26
5

行列
[[2 3]
 [7 8]]

逆行列
[[14 11]
 [17 10]]

26 を法とした
(x, y) (mod26) は
[[10]
 [11]]


### 下記は修正前

In [ ]:
#修正前
import numpy as np

#numpy配列を宣言、初期化
arr = np.array([[0, 1], [2, 3]])
arr_ab = np.array([[1], [2]])

#値を入力
arr[0][0] = int(input("a11 = "))
arr[0][1] = int(input("a12 = "))
arr[1][0] = int(input("a21 = "))
arr[1][1] = int(input("a22 = "))
arr_ab[0][0] = int(input("a = "))
arr_ab[1][0] = int(input("b = "))
mod = (int(input("mod = ")))

a = (arr[0][0] * arr[1][1]) - (arr[0][1] * arr[1][0])

#Nを法とした逆数を求める
arr_inv = np.array([[arr[1][1], -arr[0][1]], [-arr[1][0], arr[0][0]]])
ans = arr_inv * abs(a)

#最小正剰余の計算
while ans[0][0] > mod or ans[0][1] < 0 or ans[1][0] < 0 or ans[1][1] > mod:
  if ans[0][0] > mod:
    ans[0][0] -= mod

  if ans[0][1] < 0:
    ans[0][1] += mod

  if ans[1][0] < 0:
    ans[1][0] += mod

  if ans[1][1] > mod:
    ans[1][1] -= mod

#結果の出力
print()
print(arr)
print()
print("逆行列")
print(ans)
print()

#配列の積
ans1 = np.dot(ans, arr_ab)
print(ans1)
print()

#最小正剰余の計算
while ans1[0][0] > mod or ans1[0][0] < 0 or ans1[1][0] < 0 or ans1[1][0] > mod:
  if ans1[0][0] > mod:
    ans1[0][0] -= mod

  if ans1[0][0] < 0:
    ans1[0][0] += mod

  if ans1[1][0] < 0:
    ans1[1][0] += mod

  if ans1[1][0] > mod:
    ans1[1][0] -= mod

#結果の出力
print(mod,"を法とした")
print(arr)
print(arr_ab)
print("x,y", "(mod", mod, ")", "は")
print(ans1)

a11 = 5
a12 = 2
a21 = 4
a22 = 3
a = 2
b = 1
mod = 24

[[5 2]
 [4 3]]

逆行列
[[21 10]
 [20 11]]

[[52]
 [51]]

24 を法とした
[[5 2]
 [4 3]]
[[2]
 [1]]
x,y (mod 24 ) は
[[4]
 [3]]
